runtime: php73

env_variables:
  APP_DEBUG: true
  LOG_CHANNEL: stderr
  APP_STORAGE: /tmp


url: .*
script: auto
        
vpc_access_connector:
  name: projects/direktphp-310214/locations/europe-west3/connectors/direktphpapp