runtime: php73

env_variables:
  APP_DEBUG: true
  LOG_CHANNEL: stderr
  APP_STORAGE: /tmp

handlers:
- url: .*
  script: auto
        
# vpc_access_connector:
#  name: projects/my-terraform-project-316213/locations/europe-west3/connectors/terraform-webapp-3456